/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fees_management_system;
import java.awt.Color;

/**
 *
 * @author sanjay
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setTitle("Home");
        this.setIconImage(Logo.setIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_add_fee = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_search_record = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_edit_course = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_view_course = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_view_record = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_view_report = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_about = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Plot No. 1, 2, Sion - Panvel Expressway, Sector 18, Kamothe, Navi Mumbai, Maharashtra 410209");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mahatma Gandhi Mission ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("College Of Engineering And Technology");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 150));

        jPanel2.setBackground(new java.awt.Color(30, 32, 32));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_add_fee.setBackground(new java.awt.Color(18, 18, 18));
        btn_add_fee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(187, 134, 252), null, null));
        btn_add_fee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add_fee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_add_feeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_add_feeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_add_feeMousePressed(evt);
            }
        });
        btn_add_fee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/add2.png"))); // NOI18N
        btn_add_fee.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(232, 232, 232));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ADD FEES");
        btn_add_fee.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 50));

        jPanel2.add(btn_add_fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 170, 140));

        btn_search_record.setBackground(new java.awt.Color(18, 18, 18));
        btn_search_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(187, 134, 252), null, null));
        btn_search_record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_search_recordMouseExited(evt);
            }
        });
        btn_search_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(232, 232, 232));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SEARCH RECORD");
        btn_search_record.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 170, 50));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search-document.png"))); // NOI18N
        btn_search_record.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel2.add(btn_search_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 170, 140));

        btn_edit_course.setBackground(new java.awt.Color(18, 18, 18));
        btn_edit_course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(187, 134, 252), null, null));
        btn_edit_course.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit_courseMouseExited(evt);
            }
        });
        btn_edit_course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit.png"))); // NOI18N
        btn_edit_course.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(232, 232, 232));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("EDIT COURSE");
        btn_edit_course.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 50));

        jPanel2.add(btn_edit_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 170, 140));

        btn_view_course.setBackground(new java.awt.Color(18, 18, 18));
        btn_view_course.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(187, 134, 252), null, null));
        btn_view_course.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_view_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_view_courseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view_courseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view_courseMouseExited(evt);
            }
        });
        btn_view_course.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/text-book-opened-from-top-view.png"))); // NOI18N
        btn_view_course.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(232, 232, 232));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("VIEW COURSE");
        btn_view_course.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 50));

        jPanel2.add(btn_view_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 170, 140));

        btn_view_record.setBackground(new java.awt.Color(18, 18, 18));
        btn_view_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(187, 134, 252), null, null));
        btn_view_record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_view_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_view_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view_recordMouseExited(evt);
            }
        });
        btn_view_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 232, 232));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VIEW RECORD");
        btn_view_record.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 50));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btn_view_record.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jPanel2.add(btn_view_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 170, 140));

        btn_view_report.setBackground(new java.awt.Color(18, 18, 18));
        btn_view_report.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(187, 134, 252), null, null));
        btn_view_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_view_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_view_reportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view_reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view_reportMouseExited(evt);
            }
        });
        btn_view_report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view report.png"))); // NOI18N
        btn_view_report.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 90));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 232, 232));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VIEW REPORT");
        btn_view_report.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 50));

        jPanel2.add(btn_view_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 170, 140));

        btn_about.setBackground(new java.awt.Color(187, 134, 252));
        btn_about.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_aboutMouseExited(evt);
            }
        });
        btn_about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("About");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        btn_about.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        jPanel2.add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 500, 120, 50));

        btn_logout.setBackground(new java.awt.Color(187, 134, 252));
        btn_logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        btn_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Logout");
        btn_logout.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -1, 110, 50));

        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 120, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1200, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_feeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_feeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(43,41,43);
        btn_add_fee.setBackground(clr);
    }//GEN-LAST:event_btn_add_feeMouseEntered

    private void btn_add_feeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_feeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(18,18,18);
        btn_add_fee.setBackground(clr);
    }//GEN-LAST:event_btn_add_feeMouseExited

    private void btn_search_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(43,41,43);
        btn_search_record.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordMouseEntered

    private void btn_view_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_recordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(43,41,43);
        btn_view_record.setBackground(clr);
    }//GEN-LAST:event_btn_view_recordMouseEntered

    private void btn_edit_courseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(43,41,43);
        btn_edit_course.setBackground(clr);
    }//GEN-LAST:event_btn_edit_courseMouseEntered

    private void btn_view_courseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_courseMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(43,41,43);
        btn_view_course.setBackground(clr);
    }//GEN-LAST:event_btn_view_courseMouseEntered

    private void btn_view_reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_reportMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(43,41,43);
        btn_view_report.setBackground(clr);
    }//GEN-LAST:event_btn_view_reportMouseEntered

    private void btn_search_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(18,18,18);
        btn_search_record.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordMouseExited

    private void btn_view_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_recordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(18,18,18);
        btn_view_record.setBackground(clr);
    }//GEN-LAST:event_btn_view_recordMouseExited

    private void btn_edit_courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(18,18,18);
        btn_edit_course.setBackground(clr);
    }//GEN-LAST:event_btn_edit_courseMouseExited

    private void btn_view_courseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_courseMouseExited
        // TODO add your handling code here:
        Color clr = new Color(18,18,18);
        btn_view_course.setBackground(clr);
    }//GEN-LAST:event_btn_view_courseMouseExited

    private void btn_view_reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_reportMouseExited
        // TODO add your handling code here:
        Color clr = new Color(18,18,18);
        btn_view_report.setBackground(clr);
    }//GEN-LAST:event_btn_view_reportMouseExited

    private void btn_add_feeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add_feeMousePressed
        // TODO add your handling code here:
        AddFees addFees = new AddFees();
//        addFees.show();
        addFees.setVisible(true);
        addFees.setTitle("Add Fees");
        this.dispose();
    }//GEN-LAST:event_btn_add_feeMousePressed

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
//         TODO add your handling code here:
//        Color clr = new Color(43,41,43);
//        btn_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
//        Color clr = new Color(18,18,18);
//        btn_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(43,41,43);
        btn_about.setBackground(clr);
    }//GEN-LAST:event_btn_aboutMouseEntered

    private void btn_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseExited
        // TODO add your handling code here:
        Color clr = new Color(18,18,18);
        btn_about.setBackground(clr);
    }//GEN-LAST:event_btn_aboutMouseExited

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        Login_page login = new Login_page();
        login.setTitle("Login Page");
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_search_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordMouseClicked
        // TODO add your handling code here:
        SearchRecords records = new SearchRecords();
        records.setTitle("Search Record");
        records.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_search_recordMouseClicked

    private void btn_edit_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_courseMouseClicked
        // TODO add your handling code here:
        EditCourse editc = new EditCourse();
        editc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_edit_courseMouseClicked

    private void btn_view_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_recordMouseClicked
        // TODO add your handling code here:
        AllRecords allRecords = new AllRecords();
        allRecords.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_view_recordMouseClicked

    private void btn_view_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_courseMouseClicked
        // TODO add your handling code here:
        AllCourses allCourses = new AllCourses();
        allCourses.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_view_courseMouseClicked

    private void btn_view_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_reportMouseClicked
        // TODO add your handling code here:
        GenerateReport report = new GenerateReport();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_view_reportMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        CopyrightProtected copyright = new CopyrightProtected();
        copyright.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_about;
    private javax.swing.JPanel btn_add_fee;
    private javax.swing.JPanel btn_edit_course;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JPanel btn_search_record;
    private javax.swing.JPanel btn_view_course;
    private javax.swing.JPanel btn_view_record;
    private javax.swing.JPanel btn_view_report;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
