/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fees_management_system;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author sanjay
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        this.setTitle("Print Reciept");
        this.setIconImage(Logo.setIcon());
        getRecords();
    }
    
    public void getRecords(){
        try{
            Connection con = DBconnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from fees_details order by reciept_no desc fetch first 1 rows only");
            ResultSet rs = pst.executeQuery();
            
            rs.next();
            lbl_recieptNo.setText(rs.getString("reciept_no"));
            lbl_recievedFrom.setText(rs.getString("student_name"));
            lbl_rollNo.setText(rs.getString("roll_no"));
            String paymentMode = rs.getString("payment_mode");
            lbl_paymentMode.setText(paymentMode);
            
            if(paymentMode.equalsIgnoreCase("cash")){
                lbl_cheque_dd.setText("Cheque No:");
                lbl_chequeDD.setText("-");
                lbl_bankName.setText("-");
            }
            if(paymentMode.equalsIgnoreCase("cheque")){
                lbl_cheque_dd.setText("Cheque No:");
                lbl_chequeDD.setText(rs.getString("cheque_no"));
                lbl_bankName.setText(rs.getString("bank_name"));
            }
            if(paymentMode.equalsIgnoreCase("dd")){
                lbl_cheque_dd.setText("DD No:");
                lbl_chequeDD.setText(rs.getString("dd_no"));
                lbl_bankName.setText(rs.getString("bank_name"));
            }
            if(paymentMode.equalsIgnoreCase("card")){
                lbl_cheque_dd.setText("Cheque No:");
                lbl_chequeDD.setText("-");
                lbl_bankName.setText(rs.getString("bank_name"));
            }
            lbl_gstin.setText(rs.getString("gstin"));
            lbl_date.setText(rs.getString("date"));
            lbl_year1.setText(Integer.toString(rs.getInt("year1")));
            lbl_year2.setText(Integer.toString(rs.getInt("year2")));
            lbl_courseName.setText(rs.getString("course_name"));
            lbl_totalCourseAmount.setText(rs.getString("amount"));
            lbl_cgstAmount.setText(rs.getString("cgst"));
            lbl_sgstAmount.setText(rs.getString("sgst"));
            lbl_totalAmount.setText(rs.getString("total_amount"));
            lbl_totalWords.setText(rs.getString("total_in_words"));
            lbl_remark.setText(rs.getString("remark"));
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelPrint = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lbl_rollNo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_cheque_dd = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_year2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_gstin = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbl_paymentMode = new javax.swing.JLabel();
        lbl_chequeDD = new javax.swing.JLabel();
        lbl_bankName = new javax.swing.JLabel();
        lbl_recievedFrom = new javax.swing.JLabel();
        lbl_cgstAmount = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_year1 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        lbl_totalWords = new javax.swing.JLabel();
        lbl_cgst = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbl_totalAmount = new javax.swing.JLabel();
        lbl_totalCourseAmount = new javax.swing.JLabel();
        lbl_courseName = new javax.swing.JLabel();
        lbl_sgstAmount = new javax.swing.JLabel();
        lbl_sgst = new javax.swing.JLabel();
        lbl_remark = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        lbl_recieptNo = new javax.swing.JLabel();
        lbl_sgst3 = new javax.swing.JLabel();
        lbl_sgst4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_search_records = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn_edit_courses = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        btn_course_list = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        btn_view_all_record = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        btn_print = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(30, 32, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrint.setBackground(new java.awt.Color(255, 255, 255));
        panelPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 0, 3));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/mgmcetIconResized_3.png"))); // NOI18N
        panelPrint.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 110));

        lbl_rollNo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_rollNo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_rollNo.setForeground(new java.awt.Color(85, 0, 3));
        lbl_rollNo.setText("label");
        panelPrint.add(lbl_rollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 70, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(85, 0, 3));
        jLabel14.setText("MAHATMA GANDHI MISSION");
        panelPrint.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, -1));

        jPanel3.setBackground(new java.awt.Color(85, 0, 3));
        jPanel3.setForeground(new java.awt.Color(85, 0, 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        panelPrint.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 790, 4));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(85, 0, 3));
        jLabel15.setText("Website : www.mgmmumbai.ac.in");
        panelPrint.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(85, 0, 3));
        jLabel17.setText("GSTIN:");
        panelPrint.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(85, 0, 3));
        jLabel18.setText("Payment Mode:");
        panelPrint.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lbl_cheque_dd.setBackground(new java.awt.Color(255, 255, 255));
        lbl_cheque_dd.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_cheque_dd.setForeground(new java.awt.Color(85, 0, 3));
        lbl_cheque_dd.setText("cheque_dd");
        panelPrint.add(lbl_cheque_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(85, 0, 3));
        jLabel20.setText("Bank Name:");
        panelPrint.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(85, 0, 3));
        jLabel21.setText("The following payment in the college office for the year ");
        panelPrint.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 20));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(85, 0, 3));
        jLabel23.setText("reciept no:    ");
        panelPrint.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lbl_year2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_year2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_year2.setForeground(new java.awt.Color(85, 0, 3));
        lbl_year2.setText("2012");
        panelPrint.add(lbl_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(85, 0, 3));
        jLabel25.setText("Date:");
        panelPrint.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        lbl_date.setBackground(new java.awt.Color(255, 255, 255));
        lbl_date.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(85, 0, 3));
        lbl_date.setText("ASDSADAS:");
        panelPrint.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 140, -1));

        lbl_gstin.setBackground(new java.awt.Color(255, 255, 255));
        lbl_gstin.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_gstin.setForeground(new java.awt.Color(85, 0, 3));
        lbl_gstin.setText("ASDASD:");
        panelPrint.add(lbl_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 140, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(85, 0, 3));
        jLabel28.setText("MGMCET-");
        panelPrint.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        lbl_paymentMode.setBackground(new java.awt.Color(255, 255, 255));
        lbl_paymentMode.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_paymentMode.setForeground(new java.awt.Color(85, 0, 3));
        lbl_paymentMode.setText("sdsd");
        panelPrint.add(lbl_paymentMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, 20));

        lbl_chequeDD.setBackground(new java.awt.Color(255, 255, 255));
        lbl_chequeDD.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_chequeDD.setForeground(new java.awt.Color(85, 0, 3));
        lbl_chequeDD.setText("sdf");
        panelPrint.add(lbl_chequeDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, 20));

        lbl_bankName.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bankName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_bankName.setForeground(new java.awt.Color(85, 0, 3));
        lbl_bankName.setText("sdf");
        panelPrint.add(lbl_bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 200, 20));

        lbl_recievedFrom.setBackground(new java.awt.Color(255, 255, 255));
        lbl_recievedFrom.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_recievedFrom.setForeground(new java.awt.Color(85, 0, 3));
        lbl_recievedFrom.setText("sdfs");
        panelPrint.add(lbl_recievedFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 320, 20));

        lbl_cgstAmount.setBackground(new java.awt.Color(255, 255, 255));
        lbl_cgstAmount.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_cgstAmount.setForeground(new java.awt.Color(85, 0, 3));
        lbl_cgstAmount.setText("label2");
        panelPrint.add(lbl_cgstAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 90, 30));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(85, 0, 3));
        jLabel34.setText("-");
        panelPrint.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 10, -1));

        jSeparator1.setBackground(new java.awt.Color(85, 0, 3));
        jSeparator1.setForeground(new java.awt.Color(85, 0, 3));
        panelPrint.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 140, 10));

        jSeparator2.setBackground(new java.awt.Color(85, 0, 3));
        jSeparator2.setForeground(new java.awt.Color(85, 0, 3));
        panelPrint.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 780, 10));

        jSeparator3.setBackground(new java.awt.Color(85, 0, 3));
        jSeparator3.setForeground(new java.awt.Color(85, 0, 3));
        panelPrint.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 780, 10));

        lbl_year1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_year1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_year1.setForeground(new java.awt.Color(85, 0, 3));
        lbl_year1.setText("2020");
        panelPrint.add(lbl_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(85, 0, 3));
        jLabel36.setText("Sr.No");
        panelPrint.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 30));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(85, 0, 3));
        jLabel37.setText("Heads");
        panelPrint.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, 30));

        label2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        label2.setForeground(new java.awt.Color(85, 0, 3));
        label2.setText("1.");
        panelPrint.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 30));

        lbl_totalWords.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_totalWords.setForeground(new java.awt.Color(85, 0, 3));
        lbl_totalWords.setText("label");
        panelPrint.add(lbl_totalWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 400, 30));

        lbl_cgst.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbl_cgst.setForeground(new java.awt.Color(85, 0, 3));
        lbl_cgst.setText("CGST 9%");
        panelPrint.add(lbl_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, 30));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(85, 0, 3));
        jLabel38.setText("Amount (Rs)");
        panelPrint.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, 30));

        lbl_totalAmount.setBackground(new java.awt.Color(255, 255, 255));
        lbl_totalAmount.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_totalAmount.setForeground(new java.awt.Color(85, 0, 3));
        lbl_totalAmount.setText("label3");
        panelPrint.add(lbl_totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 80, 30));

        lbl_totalCourseAmount.setBackground(new java.awt.Color(255, 255, 255));
        lbl_totalCourseAmount.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_totalCourseAmount.setForeground(new java.awt.Color(85, 0, 3));
        lbl_totalCourseAmount.setText("label1");
        panelPrint.add(lbl_totalCourseAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 100, 30));

        lbl_courseName.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_courseName.setForeground(new java.awt.Color(85, 0, 3));
        lbl_courseName.setText("label1");
        panelPrint.add(lbl_courseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 120, 30));

        lbl_sgstAmount.setBackground(new java.awt.Color(255, 255, 255));
        lbl_sgstAmount.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_sgstAmount.setForeground(new java.awt.Color(85, 0, 3));
        lbl_sgstAmount.setText("label3");
        panelPrint.add(lbl_sgstAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 90, 30));

        lbl_sgst.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lbl_sgst.setForeground(new java.awt.Color(85, 0, 3));
        lbl_sgst.setText("SGST 9%");
        panelPrint.add(lbl_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, 30));

        lbl_remark.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_remark.setForeground(new java.awt.Color(85, 0, 3));
        lbl_remark.setText("label");
        panelPrint.add(lbl_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 290, 30));

        jSeparator4.setBackground(new java.awt.Color(85, 0, 3));
        jSeparator4.setForeground(new java.awt.Color(85, 0, 3));
        panelPrint.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 140, 10));

        jLabel42.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(85, 0, 3));
        jLabel42.setText("Reciever Signature");
        panelPrint.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 110, 30));

        lbl_recieptNo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_recieptNo.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_recieptNo.setForeground(new java.awt.Color(85, 0, 3));
        lbl_recieptNo.setText("asd");
        panelPrint.add(lbl_recieptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 140, 20));

        lbl_sgst3.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_sgst3.setForeground(new java.awt.Color(85, 0, 3));
        lbl_sgst3.setText("Total in words:");
        panelPrint.add(lbl_sgst3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 30));

        lbl_sgst4.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        lbl_sgst4.setForeground(new java.awt.Color(85, 0, 3));
        lbl_sgst4.setText("Remark:");
        panelPrint.add(lbl_sgst4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, 30));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(85, 0, 3));
        jLabel29.setText("Sec- 18, Kamothe, Navi Mumbai - 410209");
        panelPrint.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(85, 0, 3));
        jLabel30.setText("Tel : 022-2742 3403, 6513 8118 / 19");
        panelPrint.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(85, 0, 3));
        jLabel31.setText("Email : mgmcet@yahoo.co.in");
        panelPrint.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(85, 0, 3));
        jLabel32.setText("MAHATMA GANDHI MISSION'S ");
        panelPrint.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(111, 0, 1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("R  E  C  E  I  P  T");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel13)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelPrint.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 790, 40));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 25)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(85, 0, 3));
        jLabel33.setText("COLLEGE OF ENGINEERING & TECHNOLOGY");
        panelPrint.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(85, 0, 3));
        jLabel35.setText("Name: ");
        panelPrint.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(85, 0, 3));
        jLabel39.setText("Roll No:");
        panelPrint.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        jPanel1.add(panelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 790, 710));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Print Reciept");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 90, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 890, 700));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setBackground(new java.awt.Color(187, 134, 252));
        btn_logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_logoutMousePressed(evt);
            }
        });
        btn_logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Logout");
        btn_logout.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logoutEdited.png"))); // NOI18N
        btn_logout.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 230, 40));

        btn_home.setBackground(new java.awt.Color(187, 134, 252));
        btn_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Home");
        btn_home.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home_edited.png"))); // NOI18N
        btn_home.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jPanel2.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 40));

        btn_search_records.setBackground(new java.awt.Color(187, 134, 252));
        btn_search_records.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_search_records.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search_records.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search_recordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_search_recordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_search_recordsMouseExited(evt);
            }
        });
        btn_search_records.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Search Records");
        btn_search_records.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btn_search_records.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 40));

        jPanel2.add(btn_search_records, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 230, 40));

        btn_edit_courses.setBackground(new java.awt.Color(187, 134, 252));
        btn_edit_courses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_edit_courses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit_courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edit_coursesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_edit_coursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_edit_coursesMouseExited(evt);
            }
        });
        btn_edit_courses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Edit Courses");
        btn_edit_courses.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 40));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2_edited.png"))); // NOI18N
        btn_edit_courses.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, -1));

        jPanel2.add(btn_edit_courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 40));

        btn_edit.setBackground(new java.awt.Color(187, 134, 252));
        btn_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        btn_edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Edit");
        btn_edit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 40));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/update-30_1.png"))); // NOI18N
        btn_edit.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jPanel2.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 230, 40));

        btn_course_list.setBackground(new java.awt.Color(187, 134, 252));
        btn_course_list.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_course_list.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_course_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_course_listMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_course_listMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_course_listMouseExited(evt);
            }
        });
        btn_course_list.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Course List");
        btn_course_list.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 40));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/list_1_Edited.png"))); // NOI18N
        btn_course_list.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel2.add(btn_course_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 230, 40));

        btn_view_all_record.setBackground(new java.awt.Color(187, 134, 252));
        btn_view_all_record.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_view_all_record.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_view_all_record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_view_all_recordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_view_all_recordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_view_all_recordMouseExited(evt);
            }
        });
        btn_view_all_record.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel46.setText("View All Record");
        btn_view_all_record.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 40));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view_course_edited.png"))); // NOI18N
        btn_view_all_record.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jPanel2.add(btn_view_all_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 230, 40));

        btn_print.setBackground(new java.awt.Color(187, 134, 252));
        btn_print.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        btn_print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_printMouseExited(evt);
            }
        });
        btn_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel54.setText("Print");
        btn_print.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 60, 40));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-30.png"))); // NOI18N
        btn_print.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jPanel2.add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 230, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(189,108,245);
        btn_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
        Color clr = new Color(187,134,252);
        btn_logout.setBackground(clr);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMousePressed
        // TODO add your handling code here:
        Login_page login = new Login_page();
        login.show();
        this.dispose();
    }//GEN-LAST:event_btn_logoutMousePressed

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(189,108,245);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        Color clr = new Color(187,134,252);
        btn_home.setBackground(clr);
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_search_recordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordsMouseClicked
        // TODO add your handling code here:
        SearchRecords searchR = new SearchRecords();
        searchR.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_search_recordsMouseClicked

    private void btn_search_recordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordsMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(189,108,245);
        btn_search_records.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordsMouseEntered

    private void btn_search_recordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_recordsMouseExited
        // TODO add your handling code here:
        Color clr = new Color(187,134,252);
        btn_search_records.setBackground(clr);
    }//GEN-LAST:event_btn_search_recordsMouseExited

    private void btn_edit_coursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_coursesMouseClicked
        // TODO add your handling code here:
        EditCourse editc = new EditCourse();
        editc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_edit_coursesMouseClicked

    private void btn_edit_coursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_coursesMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(189,108,245);
        btn_edit_courses.setBackground(clr);
    }//GEN-LAST:event_btn_edit_coursesMouseEntered

    private void btn_edit_coursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edit_coursesMouseExited
        // TODO add your handling code here:
        Color clr = new Color(187,134,252);
        btn_edit_courses.setBackground(clr);
    }//GEN-LAST:event_btn_edit_coursesMouseExited

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        // TODO add your handling code here:
        UpdateFeesDetails updateDetails = new UpdateFeesDetails();
        updateDetails.show();
        this.dispose();
    }//GEN-LAST:event_btn_editMouseClicked

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(189,108,245);
        btn_edit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        // TODO add your handling code here:
        Color clr = new Color(187,134,252);
        btn_edit.setBackground(clr);
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_course_listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_course_listMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(189,108,245);
        btn_course_list.setBackground(clr);
    }//GEN-LAST:event_btn_course_listMouseEntered

    private void btn_course_listMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_course_listMouseExited
        // TODO add your handling code here:
        Color clr = new Color(187,134,252);
        btn_course_list.setBackground(clr);
    }//GEN-LAST:event_btn_course_listMouseExited

    private void btn_view_all_recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_all_recordMouseClicked
        // TODO add your handling code here:
        AllRecords records = new AllRecords();
        records.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_view_all_recordMouseClicked

    private void btn_view_all_recordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_all_recordMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(189,108,245);
        btn_view_all_record.setBackground(clr);
    }//GEN-LAST:event_btn_view_all_recordMouseEntered

    private void btn_view_all_recordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_view_all_recordMouseExited
        // TODO add your handling code here:
        Color clr = new Color(187,134,252);
        btn_view_all_record.setBackground(clr);
    }//GEN-LAST:event_btn_view_all_recordMouseExited

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.71,0.71);
                
                panelPrint.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseEntered
        // TODO add your handling code here:
        Color clr = new Color(189,108,245);
        btn_print.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseEntered

    private void btn_printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseExited
        // TODO add your handling code here:
        Color clr = new Color(187,134,252);
        btn_print.setBackground(clr);
    }//GEN-LAST:event_btn_printMouseExited

    private void btn_course_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_course_listMouseClicked
        // TODO add your handling code here:
        AllCourses allCourses = new AllCourses();
        allCourses.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_course_listMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_course_list;
    private javax.swing.JPanel btn_edit;
    private javax.swing.JPanel btn_edit_courses;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JPanel btn_print;
    private javax.swing.JPanel btn_search_records;
    private javax.swing.JPanel btn_view_all_record;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel lbl_bankName;
    private javax.swing.JLabel lbl_cgst;
    private javax.swing.JLabel lbl_cgstAmount;
    private javax.swing.JLabel lbl_chequeDD;
    private javax.swing.JLabel lbl_cheque_dd;
    private javax.swing.JLabel lbl_courseName;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_gstin;
    private javax.swing.JLabel lbl_paymentMode;
    private javax.swing.JLabel lbl_recieptNo;
    private javax.swing.JLabel lbl_recievedFrom;
    private javax.swing.JLabel lbl_remark;
    private javax.swing.JLabel lbl_rollNo;
    private javax.swing.JLabel lbl_sgst;
    private javax.swing.JLabel lbl_sgst3;
    private javax.swing.JLabel lbl_sgst4;
    private javax.swing.JLabel lbl_sgstAmount;
    private javax.swing.JLabel lbl_totalAmount;
    private javax.swing.JLabel lbl_totalCourseAmount;
    private javax.swing.JLabel lbl_totalWords;
    private javax.swing.JLabel lbl_year1;
    private javax.swing.JLabel lbl_year2;
    private javax.swing.JPanel panelPrint;
    // End of variables declaration//GEN-END:variables
}
